name: Ruff Check & Format

on:
  pull_request:
    paths:
      - '**/*.py'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ruff-autofix:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Install ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"

      - name: Run Ruff check and format (with autofix on PRs)
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ruff check --fix --exclude '**/__init__.py'
            ruff format --line-length 120
          else
            ruff check --exclude '**/__init__.py'
            ruff format --check --line-length 120
          fi

      - name: Commit and push changes (on pull requests only)
        if: github.event_name == 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "style: autofix with ruff"
            git push
          else
            echo "No changes to commit"
          fi
